name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  homebrew:
    runs-on: ubuntu-latest
    steps:
      - name: Update Homebrew formula
        uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: scrman
          formula-path: Formula/scrman.rb
          homebrew-tap: BlakeASmith/homebrew-tap
          download-url: https://github.com/BlakeASmith/scrman/archive/refs/tags/${{ github.ref_name }}.tar.gz
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}

